//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Upload
    {
        public Upload()
        {
            this.Ratings = new HashSet<Rating>();
        }
    
        public int UploadID { get; set; }
        public string category { get; set; }
        public string location { get; set; }
        public string username { get; set; }
        public double rating { get; set; }
        public string title { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
